# Generated by Django 5.0.6 on 2025-03-24 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sender_name', models.CharField(max_length=50)),
                ('sender_address', models.CharField(max_length=50)),
                ('sender_email', models.EmailField(max_length=254)),
                ('reciever_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reciever_address', models.CharField(blank=True, max_length=50, null=True)),
                ('reciever_email', models.EmailField(max_length=254)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('package', models.IntegerField(null=True)),
                ('carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_shipment', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(default='EXWA9772acb5-a7e0-480c-ORDER', max_length=30, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Processed'), (2, 'Dispatch'), (3, 'En Route '), (4, 'Delivered'), (5, 'On Hold'), (6, 'Cancelled')], default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
